-- Seed thêm sản phẩm Gundam để test phân trang (chạy sau khi đã có database)
USE gundam_store;

-- Cột ghi nhớ đăng nhập
ALTER TABLE users ADD COLUMN IF NOT EXISTS remember_token VARCHAR(64) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS remember_expires DATETIME DEFAULT NULL;

INSERT INTO products (name, price, category, image, description, old_price, type, series, scale, stock, is_featured, is_sale, status) VALUES
('Nu Gundam Ver.Ka (MG 1/100)', 1450000, 'Gundam', 'models_default_img.jpeg', 'Mô hình MG Ver.Ka Amuro Ray - chi tiết cực cao.', NULL, 'MG', 'Char''s Counterattack', '1/100', 30, 1, 0, 'active'),
('Freedom Gundam (HG 1/144)', 380000, 'Gundam', 'models_default_img.jpeg', 'Gundam SEED - Freedom với cánh spread.', NULL, 'HG', 'Gundam SEED', '1/144', 90, 1, 0, 'active'),
('Destiny Gundam (HG 1/144)', 420000, 'Gundam', 'models_default_img.jpeg', 'Gundam SEED Destiny - Shinn Asuka.', 480000, 'HG', 'Gundam SEED Destiny', '1/144', 70, 0, 1, 'active'),
('Infinite Justice Gundam (MG)', 980000, 'Gundam', 'models_default_img.jpeg', 'MG Infinite Justice với cánh biến hình.', NULL, 'MG', 'Gundam SEED Destiny', '1/100', 35, 1, 0, 'active'),
('00 Gundam (HG)', 360000, 'Gundam', 'models_default_img.jpeg', 'Gundam 00 - Setsuna F. Seiei.', NULL, 'HG', 'Gundam 00', '1/144', 85, 0, 0, 'active'),
('00 Raiser (RG 1/144)', 890000, 'Gundam', 'models_default_img.jpeg', 'RG Twin Drive System chi tiết.', 990000, 'RG', 'Gundam 00', '1/144', 40, 1, 1, 'active'),
('Qan[T] Full Saber (MG)', 1250000, 'Gundam', 'models_default_img.jpeg', 'MG Qan[T] phiên bản Full Saber.', NULL, 'MG', 'Gundam 00', '1/100', 25, 0, 0, 'active'),
('Red Frame Astray (MG)', 920000, 'Gundam', 'models_default_img.jpeg', 'MG Astray Red Frame với katana.', NULL, 'MG', 'Gundam SEED Astray', '1/100', 38, 1, 0, 'active'),
('Blue Frame D (HG)', 340000, 'Gundam', 'models_default_img.jpeg', 'HG Astray Blue Frame D.', NULL, 'HG', 'Gundam SEED Astray', '1/144', 60, 0, 0, 'active'),
('Banshee Norn (RG)', 1150000, 'Gundam', 'models_default_img.jpeg', 'RG Unicorn Banshee Norn.', 1280000, 'RG', 'Gundam Unicorn', '1/144', 28, 1, 1, 'active'),
('Full Armor Unicorn (PG)', 5800000, 'Gundam', 'models_default_img.jpeg', 'PG Full Armor Unicorn - siêu cao cấp.', NULL, 'PG', 'Gundam Unicorn', '1/60', 5, 0, 0, 'active'),
('Gundam Aerial (HG)', 390000, 'Gundam', 'models_default_img.jpeg', 'The Witch from Mercury - Aerial.', NULL, 'HG', 'Witch from Mercury', '1/144', 95, 1, 0, 'active'),
('Gundam Aerial Calibarn (HG)', 450000, 'Gundam', 'models_default_img.jpeg', 'HG Aerial Calibarn phiên bản mới.', NULL, 'HG', 'Witch from Mercury', '1/144', 55, 1, 0, 'active'),
('Gundam Pharact (HG)', 370000, 'Gundam', 'models_default_img.jpeg', 'HG Pharact phe đối thủ.', NULL, 'HG', 'Witch from Mercury', '1/144', 50, 0, 0, 'active'),
('Gundam Barbatos (HG)', 350000, 'Gundam', 'models_default_img.jpeg', 'IBO Barbatos form đầu tiên.', NULL, 'HG', 'Iron-Blooded Orphans', '1/144', 100, 1, 0, 'active'),
('Gundam Barbatos Lupus Rex (MG)', 1350000, 'Gundam', 'models_default_img.jpeg', 'MG Barbatos Lupus Rex hùng mãnh.', NULL, 'MG', 'Iron-Blooded Orphans', '1/100', 20, 1, 0, 'active'),
('Gundam Kimaris Trooper (HG)', 360000, 'Gundam', 'models_default_img.jpeg', 'HG Kimaris Trooper Gaelio Bauduin.', NULL, 'HG', 'Iron-Blooded Orphans', '1/144', 65, 0, 0, 'active'),
('Gundam Vidar (HG)', 380000, 'Gundam', 'models_default_img.jpeg', 'HG Vidar - McGillis Fareed.', 420000, 'HG', 'Iron-Blooded Orphans', '1/144', 45, 0, 1, 'active'),
('Zaku II High Mobility (HG)', 340000, 'Zaku', 'models_default_img.jpeg', 'HG Zaku II Type C cao cơ động.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 80, 0, 0, 'active'),
('Char''s Zaku II Red (HG)', 360000, 'Zaku', 'models_default_img.jpeg', 'Zaku đỏ huyền thoại của Char.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 75, 1, 0, 'active'),
('Gouf (HG)', 330000, 'Zaku', 'models_default_img.jpeg', 'HG Gouf phe Zeon.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 55, 0, 0, 'active'),
('Dom (HG)', 350000, 'Zaku', 'models_default_img.jpeg', 'HG Dom - heavy assault mobile suit.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 50, 0, 0, 'active'),
('Gundam Mk-II AEUG (RG)', 780000, 'Gundam', 'models_default_img.jpeg', 'RG Gundam Mk-II phe AEUG.', NULL, 'RG', 'Zeta Gundam', '1/144', 42, 0, 0, 'active'),
('Zeta Gundam (MG Ver.Ka)', 1680000, 'Gundam', 'models_default_img.jpeg', 'MG Ver.Ka Zeta biến hình.', NULL, 'MG', 'Zeta Gundam', '1/100', 18, 1, 0, 'active'),
('Hyaku Shiki (MG)', 1050000, 'Gundam', 'models_default_img.jpeg', 'MG Hyaku Shiki màu vàng gold.', 1180000, 'MG', 'Zeta Gundam', '1/100', 22, 0, 1, 'active'),
('Wing Gundam (HG)', 340000, 'Gundam', 'models_default_img.jpeg', 'HG Wing Gundam Heero Yuy.', NULL, 'HG', 'Gundam Wing', '1/144', 70, 0, 0, 'active'),
('Deathscythe Hell (MG)', 980000, 'Gundam', 'models_default_img.jpeg', 'MG Deathscythe Hell Duo Maxwell.', NULL, 'MG', 'Gundam Wing', '1/100', 30, 1, 0, 'active'),
('Heavyarms Custom (HG)', 350000, 'Gundam', 'models_default_img.jpeg', 'HG Heavyarms Custom hỏa lực.', NULL, 'HG', 'Gundam Wing', '1/144', 48, 0, 0, 'active'),
('Gundam X (HG)', 320000, 'Gundam', 'models_default_img.jpeg', 'HG Gundam X After War.', NULL, 'HG', 'After War Gundam X', '1/144', 40, 0, 0, 'active'),
('Turn A Gundam (HG)', 380000, 'Gundam', 'models_default_img.jpeg', 'HG Turn A - thiết kế độc đáo.', NULL, 'HG', 'Turn A Gundam', '1/144', 35, 0, 0, 'active'),
('G Gundam Shining Finger (HG)', 360000, 'Gundam', 'models_default_img.jpeg', 'HG Shining Gundam Domon Kasshu.', NULL, 'HG', 'G Gundam', '1/144', 45, 0, 0, 'active'),
('God Gundam (RG)', 950000, 'Gundam', 'models_default_img.jpeg', 'RG God Gundam - Shining Finger!', NULL, 'RG', 'G Gundam', '1/144', 32, 1, 0, 'active'),
('Penelope (HG)', 520000, 'Gundam', 'models_default_img.jpeg', 'HG Penelope Hathaway''s Flash.', NULL, 'HG', 'Hathaway''s Flash', '1/144', 25, 0, 0, 'active'),
('Xi Gundam (HG)', 480000, 'Gundam', 'models_default_img.jpeg', 'HG Xi Gundam - Minovsky Flight.', NULL, 'HG', 'Hathaway''s Flash', '1/144', 28, 0, 0, 'active'),
('Guncannon (HG)', 310000, 'Gundam', 'models_default_img.jpeg', 'HG Guncannon Universal Century.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 88, 0, 0, 'active'),
('Guntank (HG)', 300000, 'Gundam', 'models_default_img.jpeg', 'HG Guntank - support unit cổ điển.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 92, 0, 0, 'active'),
('GM (HG)', 280000, 'Gundam', 'models_default_img.jpeg', 'HG GM mass production unit.', NULL, 'HG', 'Mobile Suit Gundam', '1/144', 110, 0, 0, 'active'),
('Gundam GP01Fb (MG)', 890000, 'Gundam', 'models_default_img.jpeg', 'MG GP01Fb Full Burnern 0083.', NULL, 'MG', 'Gundam 0083', '1/100', 26, 0, 0, 'active'),
('Gundam GP02A (MG)', 920000, 'Gundam', 'models_default_img.jpeg', 'MG GP02A với nuclear warhead.', 1020000, 'MG', 'Gundam 0083', '1/100', 20, 0, 1, 'active'),
('GP03S Dendrobium Stamen (HG)', 450000, 'Gundam', 'models_default_img.jpeg', 'HG GP03S Stamen 0083.', NULL, 'HG', 'Gundam 0083', '1/144', 35, 0, 0, 'active'),
('Sinanju Stein (HG)', 420000, 'Gundam', 'models_default_img.jpeg', 'HG Sinanju Stein Narrative.', NULL, 'HG', 'Gundam Narrative', '1/144', 38, 0, 0, 'active'),
('Narrative Gundam (HG)', 390000, 'Gundam', 'models_default_img.jpeg', 'HG Narrative Gundam C-Packs.', NULL, 'HG', 'Gundam Narrative', '1/144', 42, 0, 0, 'active'),
('G-Self Perfect Pack (HG)', 480000, 'Gundam', 'models_default_img.jpeg', 'HG G-Self Reconguista in G.', NULL, 'HG', 'Reconguista in G', '1/144', 30, 0, 0, 'active'),
('SD Gundam World Sangoku Soketsuden Liu Bei Unicorn', 220000, 'Gundam', 'models_default_img.jpeg', 'SD crossover Sangoku Soketsuden.', NULL, 'SD', 'SD Gundam World', 'SD', 150, 0, 0, 'active'),
('SD BB Senshi Victory Gundam', 200000, 'Gundam', 'models_default_img.jpeg', 'SD BB Senshi cổ điển.', NULL, 'SD', 'Victory Gundam', 'SD', 180, 0, 0, 'active'),
('PG Strike Freedom Gundam', 7200000, 'Gundam', 'models_default_img.jpeg', 'PG Strike Freedom cánh angel wings.', NULL, 'PG', 'Gundam SEED Destiny', '1/60', 6, 1, 0, 'active'),
('PG Wing Gundam Zero Custom', 6800000, 'Gundam', 'models_default_img.jpeg', 'PG Wing Zero Custom EW.', NULL, 'PG', 'Gundam Wing EW', '1/60', 4, 0, 0, 'active'),
('MGEX Unicorn Gundam', 2100000, 'Gundam', 'models_default_img.jpeg', 'MGEX Unicorn Psycho-Frame LED.', NULL, 'MGEX', 'Gundam Unicorn', '1/100', 12, 1, 0, 'active'),
('MGEX Infinite Justice Gundam', 2250000, 'Gundam', 'models_default_img.jpeg', 'MGEX Infinite Justice cao cấp.', NULL, 'MGEX', 'Gundam SEED Destiny', '1/100', 10, 1, 0, 'active'),
('RG Hi-Nu Gundam', 1380000, 'Gundam', 'models_default_img.jpeg', 'RG Hi-Nu Ver.Ka Amuro Ray.', 1500000, 'RG', 'Char''s Counterattack', '1/144', 22, 1, 1, 'active'),
('RG Nu Gundam', 1250000, 'Gundam', 'models_default_img.jpeg', 'RG Nu Gundam funnel system.', NULL, 'RG', 'Char''s Counterattack', '1/144', 25, 1, 0, 'active'),
('HG Gundam Calamity', 400000, 'Gundam', 'models_default_img.jpeg', 'HG Calamity Gundam SEED.', NULL, 'HG', 'Gundam SEED', '1/144', 58, 0, 0, 'active'),
('HG Gundam Forbidden', 390000, 'Gundam', 'models_default_img.jpeg', 'HG Forbidden Gundam phase shift.', NULL, 'HG', 'Gundam SEED', '1/144', 52, 0, 0, 'active'),
('HG Gundam Raider', 380000, 'Gundam', 'models_default_img.jpeg', 'HG Raider Gundam heavy assault.', NULL, 'HG', 'Gundam SEED', '1/144', 48, 0, 0, 'active'),
('MG Providence Gundam', 1150000, 'Gundam', 'models_default_img.jpeg', 'MG Providence Rau Le Creuset.', 1280000, 'MG', 'Gundam SEED', '1/100', 24, 0, 1, 'active'),
('HG Gundam AGE-1 Normal', 320000, 'Gundam', 'models_default_img.jpeg', 'HG AGE-1 Normal Flit Asuno.', NULL, 'HG', 'Gundam AGE', '1/144', 44, 0, 0, 'active'),
('HG Gundam AGE-2 Normal', 340000, 'Gundam', 'models_default_img.jpeg', 'HG AGE-2 biến hình.', NULL, 'HG', 'Gundam AGE', '1/144', 40, 0, 0, 'active'),
('HG Gundam F91', 350000, 'Gundam', 'models_default_img.jpeg', 'HG F91 Seabook Arno.', NULL, 'HG', 'Gundam F91', '1/144', 36, 0, 0, 'active'),
('MG Crossbone Gundam X1', 780000, 'Gundam', 'models_default_img.jpeg', 'MG Crossbone X1 pirate Gundam.', NULL, 'MG', 'Crossbone Gundam', '1/100', 28, 0, 0, 'active');
